#!/bin/bash

read -p $'Enter START_DATE:\n' START_DATE
read -p $'Enter END_DATE:\n' END_DATE
read -p $'Enter LOCATION:\n' LOCATION
read -p $'Enter API_KEY:\n' API_KEY
read -p $'Enter GOOGLE_APPLICATION_CREDENTIALS_PATH:\n' GOOGLE_APPLICATION_CREDENTIALS_PATH
read -p $'Enter BIG_QUERY_TARGET_ID:\n' BIG_QUERY_TARGET_ID

python main.py "$START_DATE" "$END_DATE" "$LOCATION" "$API_KEY" "$GOOGLE_APPLICATION_CREDENTIALS_PATH" "$BIG_QUERY_TARGET_ID"
